version: "3.9"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - "./db_scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db_scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 50
  user:
    build: ./user/.
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8100/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 50
      start_period: 30s
    ports:
      - "8100:8100"
  product:
    build: ./product/.
    depends_on:
      mysql:
        condition: service_healthy
      user:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 50
      start_period: 30s
    ports:
      - "8080:8080"
  order:
    build: ./order/.
    depends_on:
      mysql:
        condition: service_healthy
      user:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 50
      start_period: 30s
    ports:
      - "8090:8090"
  web:
    build: ./web/.
    depends_on:
      user:
        condition: service_healthy
      product:
        condition: service_healthy
      order:
        condition: service_healthy
    ports:
      - "8081:8081"
